// ── Upgrade Node Definitions ─────────────────────────────────
// Data-driven node/mod definitions for in-run build crafting.
// Each node modifies player.combatMods when applied.
//
// Categories:
//   melee, dagger, dash, ability:<id>, proc:<id>, global
//
// Rarity: common, uncommon, rare, epic, legendary
// ─────────────────────────────────────────────────────────────

import {
    NODE_RARITY_COMMON, NODE_RARITY_UNCOMMON, NODE_RARITY_RARE,
    NODE_RARITY_EPIC, NODE_RARITY_LEGENDARY,
} from '../constants.js';

// ── Node Registry ──

export const NODE_DEFINITIONS = {

    // ═══════════════════════════════════════════════════
    // MELEE NODES
    // ═══════════════════════════════════════════════════

    melee_cleave: {
        id: 'melee_cleave',
        name: 'Cleave',
        desc: '+1 extra melee target',
        icon: '⚔️',
        color: '#f44336',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.extraTargets = (mods.melee.extraTargets || 0) + 1; },
    },
    melee_arc_wider: {
        id: 'melee_arc_wider',
        name: 'Wide Arc',
        desc: '+20% attack arc',
        icon: '🌀',
        color: '#ff9800',
        category: 'melee',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.arcMult = (mods.melee.arcMult || 1) * 1.20; },
    },
    melee_attack_speed: {
        id: 'melee_attack_speed',
        name: 'Quick Strikes',
        desc: '+15% attack speed',
        icon: '⚡',
        color: '#ffeb3b',
        category: 'melee',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.cooldownMult = (mods.melee.cooldownMult || 1) * 0.85; },
    },
    melee_stun_chance: {
        id: 'melee_stun_chance',
        name: 'Staggering Blows',
        desc: '10% chance stun 0.5s',
        icon: '💫',
        color: '#9c27b0',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.stunChance = 0.10; mods.melee.stunDuration = 500; },
    },
    melee_bleed: {
        id: 'melee_bleed',
        name: 'Serrated Edge',
        desc: '20% bleed for 2s',
        icon: '🩸',
        color: '#e91e63',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.bleedChance = 0.20; mods.melee.bleedDuration = 2000; mods.melee.bleedDps = 5; },
    },
    melee_kill_nova: {
        id: 'melee_kill_nova',
        name: 'Kill Nova',
        desc: 'On kill: small AoE burst (1s CD)',
        icon: '💥',
        color: '#ff5722',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.melee.killNova = true; mods.melee.killNovaCooldown = 1000; mods.melee.killNovaRadius = 60; mods.melee.killNovaDmgMult = 0.4; },
    },
    melee_heavy_hit: {
        id: 'melee_heavy_hit',
        name: 'Heavy Strike',
        desc: '+30% knockback, -10% speed',
        icon: '🔨',
        color: '#795548',
        category: 'melee',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.knockbackMult = (mods.melee.knockbackMult || 1) * 1.30; mods.melee.cooldownMult = (mods.melee.cooldownMult || 1) * 1.10; },
    },
    melee_lunge: {
        id: 'melee_lunge',
        name: 'Lunge',
        desc: 'Small forward lunge on attack',
        icon: '🏃',
        color: '#2196f3',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.lunge = true; mods.melee.lungeDistance = 30; },
    },
    melee_vampiric: {
        id: 'melee_vampiric',
        name: 'Vampiric Edge',
        desc: 'Heal 8% of melee damage dealt',
        icon: '🧛',
        color: '#b71c1c',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.lifestealPct = (mods.melee.lifestealPct || 0) + 0.08; },
    },
    melee_chain_kill: {
        id: 'melee_chain_kill',
        name: 'Chain Fury',
        desc: 'Kills grant +50% DMG for 2s',
        icon: '🔗',
        color: '#d32f2f',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.chainKillBuff = true; mods.melee.chainKillDmgMult = 1.5; mods.melee.chainKillDuration = 2000; },
    },
    melee_quake: {
        id: 'melee_quake',
        name: 'Earthquake Slam',
        desc: 'Every 5th hit: massive AoE groundpound',
        icon: '🌋',
        color: '#ff3d00',
        category: 'melee',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.melee.quakeEveryN = 5; mods.melee.quakeRadius = 120; mods.melee.quakeDmgMult = 0.8; },
    },
    melee_whirlwind: {
        id: 'melee_whirlwind',
        name: 'Whirlwind Strike',
        desc: 'Attacks hit 360° but 20% slower',
        icon: '🌪️',
        color: '#ff6f00',
        category: 'melee',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.melee.arcMult = (mods.melee.arcMult || 1) * 3.0; mods.melee.cooldownMult = (mods.melee.cooldownMult || 1) * 1.20; },
    },
    melee_razor_orbit: {
        id: 'melee_razor_orbit',
        name: 'Razor Orbit',
        desc: 'Melee kills spawn orbiting blade (15s)',
        icon: '🔆',
        color: '#ef5350',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.razorOrbitMax = (mods.melee.razorOrbitMax || 0) + 1; mods.melee.razorOrbitDmgMult = 0.25; mods.melee.razorOrbitDuration = 15000; },
    },

    // ── NEW MELEE NODES ──

    melee_iron_fists: {
        id: 'melee_iron_fists',
        name: 'Iron Fists',
        desc: '+10% melee damage',
        icon: '✊',
        color: '#b0bec5',
        category: 'melee',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 3,
        apply(mods, stacks) { mods.melee.damageMult = (mods.melee.damageMult || 1) * 1.10; },
    },
    melee_siphon_strike: {
        id: 'melee_siphon_strike',
        name: 'Siphon Strike',
        desc: 'Kills restore 3% max HP',
        icon: '💉',
        color: '#c62828',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.melee.killHealPct = (mods.melee.killHealPct || 0) + 0.03; },
    },
    melee_berserker_frenzy: {
        id: 'melee_berserker_frenzy',
        name: 'Berserker Frenzy',
        desc: 'Below 50% HP: +25% attack speed',
        icon: '🔴',
        color: '#d50000',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.melee.lowHpAttackSpeed = true; mods.melee.lowHpThreshold = 0.50; mods.melee.lowHpSpeedMult = 0.75; },
    },
    melee_executioner_mark: {
        id: 'melee_executioner_mark',
        name: "Executioner's Mark",
        desc: '+20% melee DMG to enemies below 30% HP',
        icon: '☠️',
        color: '#880e4f',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.executeMult = 1.20; mods.melee.executeThreshold = 0.30; },
    },
    melee_afterimage: {
        id: 'melee_afterimage',
        name: 'Afterimage',
        desc: '15% chance: delayed ghost strike (40% DMG)',
        icon: '👤',
        color: '#78909c',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.melee.afterimage = true; mods.melee.afterimageChance = 0.15; mods.melee.afterimageDmgMult = 0.40; mods.melee.afterimageDelay = 300; },
    },
    melee_echo_strike: {
        id: 'melee_echo_strike',
        name: 'Echo Strike',
        desc: '15% chance: attack hits twice',
        icon: '🔁',
        color: '#5c6bc0',
        category: 'melee',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.melee.echoChance = 0.15; },
    },
    melee_riposte: {
        id: 'melee_riposte',
        name: 'Riposte',
        desc: 'After taking damage, next melee crits (3s)',
        icon: '⚔️',
        color: '#ffc107',
        category: 'melee',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.melee.riposte = true; mods.melee.riposteWindow = 3000; },
    },
    melee_tempest_blade: {
        id: 'melee_tempest_blade',
        name: 'Tempest Blade',
        desc: 'Every 3rd swing fires a projectile wave',
        icon: '🌊',
        color: '#0277bd',
        category: 'melee',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.melee.tempestEveryN = 3; mods.melee.tempestDmgMult = 0.50; mods.melee.tempestRange = 200; },
    },
    melee_relentless: {
        id: 'melee_relentless',
        name: 'Relentless',
        desc: 'Hitting 3+ enemies resets attack cooldown',
        icon: '♾️',
        color: '#e65100',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.relentlessThreshold = 3; },
    },
    melee_impact_armor: {
        id: 'melee_impact_armor',
        name: 'Impact Armor',
        desc: 'Melee hits grant 3% DR for 2s (max 15%)',
        icon: '🛡️',
        color: '#546e7a',
        category: 'melee',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.melee.impactArmor = true; mods.melee.impactArmorPer = 0.03; mods.melee.impactArmorMax = 0.15; mods.melee.impactArmorDuration = 2000; },
    },

    // ═══════════════════════════════════════════════════
    // DAGGER NODES
    // ═══════════════════════════════════════════════════

    dagger_extra_projectile: {
        id: 'dagger_extra_projectile',
        name: 'Multi-Dagger',
        desc: '+1 dagger per throw',
        icon: '🗡️',
        color: '#4fc3f7',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dagger.extraProjectiles = (mods.dagger.extraProjectiles || 0) + 1; },
    },
    dagger_spread: {
        id: 'dagger_spread',
        name: 'Fan of Knives',
        desc: 'Daggers shoot in 3-way cone',
        icon: '🌊',
        color: '#00bcd4',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.spreadPattern = true; mods.dagger.spreadCount = 3; mods.dagger.spreadArc = 0.4; },
    },
    dagger_pierce: {
        id: 'dagger_pierce',
        name: 'Piercing Daggers',
        desc: '+1 pierce',
        icon: '📌',
        color: '#8bc34a',
        category: 'dagger',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 3,
        apply(mods, stacks) { mods.dagger.pierce = (mods.dagger.pierce || 0) + 1; },
    },
    dagger_ricochet: {
        id: 'dagger_ricochet',
        name: 'Ricochet',
        desc: '+1 bounce off walls',
        icon: '🔄',
        color: '#ff9800',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dagger.ricochet = (mods.dagger.ricochet || 0) + 1; },
    },
    dagger_fire_trail: {
        id: 'dagger_fire_trail',
        name: 'Fire Trail',
        desc: 'Daggers leave burn trail (1.2s)',
        icon: '🔥',
        color: '#ff6d00',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.fireTrail = true; mods.dagger.fireTrailDuration = 1200; mods.dagger.fireTrailDps = 4; },
    },
    dagger_speed: {
        id: 'dagger_speed',
        name: 'Swift Throw',
        desc: '+25% dagger speed',
        icon: '💨',
        color: '#03a9f4',
        category: 'dagger',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dagger.speedMult = (mods.dagger.speedMult || 1) * 1.25; },
    },
    dagger_crit: {
        id: 'dagger_crit',
        name: 'Precision Throw',
        desc: '+5% crit chance (daggers)',
        icon: '🎯',
        color: '#ff1744',
        category: 'dagger',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dagger.critBonus = (mods.dagger.critBonus || 0) + 0.05; },
    },
    dagger_returning: {
        id: 'dagger_returning',
        name: 'Boomerang',
        desc: 'Daggers return to you',
        icon: '🪃',
        color: '#7c4dff',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.returning = true; },
    },
    dagger_explosive: {
        id: 'dagger_explosive',
        name: 'Explosive Daggers',
        desc: 'Daggers explode on final hit (r60)',
        icon: '💣',
        color: '#ff6d00',
        category: 'dagger',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dagger.explosive = true; mods.dagger.explosionRadius = 60; mods.dagger.explosionDmgMult = 0.5; },
    },
    dagger_homing: {
        id: 'dagger_homing',
        name: 'Homing Daggers',
        desc: 'Daggers gently track enemies',
        icon: '🎯',
        color: '#00e676',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.homing = true; mods.dagger.homingStrength = 2.0; },
    },
    dagger_shadow: {
        id: 'dagger_shadow',
        name: 'Shadow Daggers',
        desc: 'Daggers spawn a ghost copy after 0.3s',
        icon: '👻',
        color: '#9e9e9e',
        category: 'dagger',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dagger.shadowCopy = true; mods.dagger.shadowDelay = 300; mods.dagger.shadowDmgMult = 0.4; },
    },
    dagger_venom: {
        id: 'dagger_venom',
        name: 'Venomous Tips',
        desc: 'Daggers slow enemies 30% for 1.5s',
        icon: '🐍',
        color: '#76ff03',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dagger.venomSlow = true; mods.dagger.venomSlowFactor = 0.7; mods.dagger.venomSlowDuration = 1500; },
    },

    // ── NEW DAGGER NODES ──

    dagger_damage: {
        id: 'dagger_damage',
        name: 'Dagger Mastery',
        desc: '+12% dagger damage',
        icon: '🗡️',
        color: '#b3e5fc',
        category: 'dagger',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 3,
        apply(mods, stacks) { mods.dagger.damageMult = (mods.dagger.damageMult || 1) * 1.12; },
    },
    dagger_frozen_tips: {
        id: 'dagger_frozen_tips',
        name: 'Frozen Tips',
        desc: 'Daggers freeze enemies 0.4s on hit',
        icon: '❄️',
        color: '#4dd0e1',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dagger.freezeOnHit = true; mods.dagger.freezeDuration = 400; },
    },
    dagger_assassin_mark: {
        id: 'dagger_assassin_mark',
        name: "Assassin's Mark",
        desc: '+30% dagger DMG to enemies below 30% HP',
        icon: '🎯',
        color: '#ad1457',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dagger.executeMult = 1.30; mods.dagger.executeThreshold = 0.30; },
    },
    dagger_barrage: {
        id: 'dagger_barrage',
        name: 'Barrage',
        desc: 'Double throw rate, -15% damage each',
        icon: '⏩',
        color: '#0097a7',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.cooldownMult = (mods.dagger.cooldownMult || 1) * 0.50; mods.dagger.damageMult = (mods.dagger.damageMult || 1) * 0.85; },
    },
    dagger_spectral: {
        id: 'dagger_spectral',
        name: 'Spectral Daggers',
        desc: 'Daggers pass through walls',
        icon: '👻',
        color: '#b39ddb',
        category: 'dagger',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dagger.phaseThrough = true; },
    },
    dagger_rain: {
        id: 'dagger_rain',
        name: 'Rain of Knives',
        desc: 'Every 8s: auto-fire daggers in all directions',
        icon: '🌧️',
        color: '#006064',
        category: 'dagger',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.dagger.autoRain = true; mods.dagger.autoRainInterval = 8000; mods.dagger.autoRainCount = 8; mods.dagger.autoRainDmgMult = 0.30; },
    },
    dagger_chain_throw: {
        id: 'dagger_chain_throw',
        name: 'Chain Throw',
        desc: 'Dagger hits fire 1 extra at nearest enemy',
        icon: '🔗',
        color: '#26c6da',
        category: 'dagger',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dagger.chainThrow = true; mods.dagger.chainThrowDmgMult = 0.50; },
    },
    dagger_bleed: {
        id: 'dagger_bleed',
        name: 'Serrated Daggers',
        desc: 'Daggers apply bleed (3 DPS, 1.5s)',
        icon: '🩸',
        color: '#ef5350',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dagger.bleedOnHit = true; mods.dagger.bleedDps = 3; mods.dagger.bleedDuration = 1500; },
    },
    dagger_gravity_pull: {
        id: 'dagger_gravity_pull',
        name: 'Magnetic Daggers',
        desc: 'Daggers pull enemies slightly toward impact',
        icon: '🧲',
        color: '#7e57c2',
        category: 'dagger',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dagger.pullOnHit = true; mods.dagger.pullForce = 20; },
    },
    dagger_rapid_fire: {
        id: 'dagger_rapid_fire',
        name: 'Rapid Fire',
        desc: '-20% dagger cooldown',
        icon: '💨',
        color: '#0288d1',
        category: 'dagger',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dagger.cooldownMult = (mods.dagger.cooldownMult || 1) * 0.80; },
    },

    // ═══════════════════════════════════════════════════
    // DASH NODES
    // ═══════════════════════════════════════════════════

    dash_end_shockwave: {
        id: 'dash_end_shockwave',
        name: 'Impact Dash',
        desc: 'AoE + knockback at dash end',
        icon: '💥',
        color: '#ff9800',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.endShockwave = true; mods.dash.endShockwaveRadius = 50; mods.dash.endShockwaveKb = 15; },
    },
    dash_fire_trail: {
        id: 'dash_fire_trail',
        name: 'Blazing Dash',
        desc: 'Leave a fire trail when dashing',
        icon: '🔥',
        color: '#ff6d00',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.fireTrail = true; mods.dash.fireTrailDps = 6; mods.dash.fireTrailDuration = 800; },
    },
    dash_cooldown_reduction: {
        id: 'dash_cooldown_reduction',
        name: 'Quick Recovery',
        desc: '-15% dash cooldown',
        icon: '⏱️',
        color: '#2196f3',
        category: 'dash',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dash.cooldownMult = (mods.dash.cooldownMult || 1) * 0.85; },
    },
    dash_longer: {
        id: 'dash_longer',
        name: 'Extended Roll',
        desc: '+20% dash distance',
        icon: '📏',
        color: '#4caf50',
        category: 'dash',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dash.durationMult = (mods.dash.durationMult || 1) * 1.20; },
    },
    dash_stun: {
        id: 'dash_stun',
        name: 'Stunning Rush',
        desc: 'Dash collision stuns 0.4s',
        icon: '💫',
        color: '#9c27b0',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.stunOnHit = true; mods.dash.stunDuration = 400; },
    },
    dash_extra_charge: {
        id: 'dash_extra_charge',
        name: 'Double Dash',
        desc: '+1 dash charge (can chain dashes!)',
        icon: '⚡',
        color: '#00e5ff',
        category: 'dash',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 2,
        apply(mods, stacks) { mods.dash.extraCharges = (mods.dash.extraCharges || 0) + 1; },
    },
    dash_phantom_trail: {
        id: 'dash_phantom_trail',
        name: 'Phantom Trail',
        desc: 'Dash leaves damaging afterimages',
        icon: '👻',
        color: '#b388ff',
        category: 'dash',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dash.phantomTrail = true; mods.dash.phantomDmgMult = 0.35; mods.dash.phantomDuration = 600; },
    },
    dash_void_rift: {
        id: 'dash_void_rift',
        name: 'Void Rift',
        desc: 'Dash leaves a vortex that pulls enemies',
        icon: '🌀',
        color: '#7c4dff',
        category: 'dash',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dash.voidRift = true; mods.dash.voidRiftRadius = 80; mods.dash.voidRiftDuration = 1500; mods.dash.voidRiftForce = 150; },
    },
    dash_kill_reset: {
        id: 'dash_kill_reset',
        name: 'Dash Reset',
        desc: 'Kills instantly reset dash cooldown',
        icon: '♻️',
        color: '#00c853',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.killReset = true; },
    },

    // ── NEW DASH NODES ──

    dash_speed_boost: {
        id: 'dash_speed_boost',
        name: 'Nimble Roll',
        desc: '+15% dash speed',
        icon: '💨',
        color: '#4db6ac',
        category: 'dash',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.dash.speedMult = (mods.dash.speedMult || 1) * 1.15; },
    },
    dash_shadow_step: {
        id: 'dash_shadow_step',
        name: 'Shadow Step',
        desc: '0.3s invulnerability after dash ends',
        icon: '🌑',
        color: '#37474f',
        category: 'dash',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dash.postInvuln = true; mods.dash.postInvulnDuration = 300; },
    },
    dash_momentum_strike: {
        id: 'dash_momentum_strike',
        name: 'Momentum Strike',
        desc: 'First melee after dash does +40% DMG',
        icon: '💪',
        color: '#ff6f00',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.momentumStrike = true; mods.dash.momentumStrikeMult = 1.40; mods.dash.momentumStrikeWindow = 1500; },
    },
    dash_afterburn: {
        id: 'dash_afterburn',
        name: 'Afterburn',
        desc: 'Enemies near dash path take 15 DMG',
        icon: '🔥',
        color: '#ff5722',
        category: 'dash',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.dash.afterburn = true; mods.dash.afterburnDamage = 15; mods.dash.afterburnRadius = 40; },
    },
    dash_phase_strike: {
        id: 'dash_phase_strike',
        name: 'Phase Strike',
        desc: 'Dashing through enemies damages them',
        icon: '⚡',
        color: '#e040fb',
        category: 'dash',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.dash.phaseStrike = true; mods.dash.phaseStrikeDmgMult = 0.50; },
    },
    dash_mirror_image: {
        id: 'dash_mirror_image',
        name: 'Mirror Image',
        desc: 'Dash creates a decoy that taunts (3s)',
        icon: '🪞',
        color: '#90caf9',
        category: 'dash',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.dash.mirrorImage = true; mods.dash.mirrorDuration = 3000; },
    },

    // ═══════════════════════════════════════════════════
    // ABILITY-SPECIFIC: SHOCKWAVE
    // ═══════════════════════════════════════════════════

    shockwave_radius: {
        id: 'shockwave_radius',
        name: 'Wider Blast',
        desc: '+30% shockwave radius',
        icon: '💥',
        color: '#ff9800',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['shockwave'] },
        apply(mods, stacks) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.radiusMult = (mods.abilities.shockwave.radiusMult || 1) * 1.30; },
    },
    shockwave_double_pulse: {
        id: 'shockwave_double_pulse',
        name: 'Aftershock',
        desc: 'Second pulse after 0.3s (60% DMG)',
        icon: '🔄',
        color: '#ff5722',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.doublePulse = true; mods.abilities.shockwave.secondPulseDmgMult = 0.6; mods.abilities.shockwave.secondPulseDelay = 300; },
    },
    shockwave_stun: {
        id: 'shockwave_stun',
        name: 'Concussive Blast',
        desc: 'Stun 0.6s in inner radius',
        icon: '💫',
        color: '#ffd700',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.stunDuration = 600; mods.abilities.shockwave.stunInnerRadius = 0.5; },
    },
    shockwave_cd: {
        id: 'shockwave_cd',
        name: 'Seismic Affinity',
        desc: '-20% shockwave cooldown',
        icon: '⏱️',
        color: '#ff9800',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.cooldownMult = (mods.abilities.shockwave.cooldownMult || 1) * 0.80; },
    },
    shockwave_chain_reaction: {
        id: 'shockwave_chain_reaction',
        name: 'Chain Reaction',
        desc: 'Killed enemies explode for 40% DMG',
        icon: '💥',
        color: '#ff3d00',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.chainReaction = true; mods.abilities.shockwave.chainDmgMult = 0.4; mods.abilities.shockwave.chainRadius = 70; },
    },
    shockwave_scorching: {
        id: 'shockwave_scorching',
        name: 'Scorching Wave',
        desc: 'Shockwave ignites enemies (4 DPS, 2s)',
        icon: '🔥',
        color: '#ff6d00',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.burnOnHit = true; mods.abilities.shockwave.burnDps = 4; mods.abilities.shockwave.burnDuration = 2000; },
    },
    shockwave_pull: {
        id: 'shockwave_pull',
        name: 'Gravity Shock',
        desc: 'Shockwave pulls enemies inward first',
        icon: '🌑',
        color: '#e040fb',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.pullBefore = true; mods.abilities.shockwave.pullForce = 180; },
    },

    // ── NEW SHOCKWAVE NODES ──

    shockwave_tremor: {
        id: 'shockwave_tremor',
        name: 'Tremor',
        desc: 'Shockwave slows all hit enemies (1.5s)',
        icon: '🌍',
        color: '#a1887f',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.slowOnHit = true; mods.abilities.shockwave.slowDuration = 1500; mods.abilities.shockwave.slowFactor = 0.5; },
    },
    shockwave_fortify: {
        id: 'shockwave_fortify',
        name: 'Fortify',
        desc: 'Shockwave grants +15% DR for 3s',
        icon: '🛡️',
        color: '#42a5f5',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.fortify = true; mods.abilities.shockwave.fortifyDR = 0.15; mods.abilities.shockwave.fortifyDuration = 3000; },
    },
    shockwave_ground_fire: {
        id: 'shockwave_ground_fire',
        name: 'Scorched Earth',
        desc: 'Shockwave leaves burning ground (3s)',
        icon: '🔥',
        color: '#bf360c',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['shockwave'] },
        apply(mods) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.groundFire = true; mods.abilities.shockwave.groundFireDps = 3; mods.abilities.shockwave.groundFireDuration = 3000; },
    },
    shockwave_empowered: {
        id: 'shockwave_empowered',
        name: 'Empowered Wave',
        desc: '+20% shockwave damage',
        icon: '💥',
        color: '#e65100',
        category: 'ability:shockwave',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['shockwave'] },
        apply(mods, stacks) { mods.abilities.shockwave = mods.abilities.shockwave || {}; mods.abilities.shockwave.dmgMult = (mods.abilities.shockwave.dmgMult || 1) * 1.20; },
    },

    // ═══════════════════════════════════════════════════
    // ABILITY-SPECIFIC: BLADE STORM
    // ═══════════════════════════════════════════════════

    bladestorm_duration: {
        id: 'bladestorm_duration',
        name: 'Prolonged Storm',
        desc: '+1s blade storm duration',
        icon: '🌀',
        color: '#e040fb',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['blade_storm'] },
        apply(mods, stacks) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.durationBonus = (mods.abilities.blade_storm.durationBonus || 0) + 1; },
    },
    bladestorm_radius: {
        id: 'bladestorm_radius',
        name: 'Expanding Vortex',
        desc: '+15% blade storm radius',
        icon: '🌀',
        color: '#ce93d8',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['blade_storm'] },
        apply(mods, stacks) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.radiusMult = (mods.abilities.blade_storm.radiusMult || 1) * 1.15; },
    },
    bladestorm_cd: {
        id: 'bladestorm_cd',
        name: 'Storm Mastery',
        desc: '-15% blade storm cooldown',
        icon: '⏱️',
        color: '#e040fb',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.cooldownMult = (mods.abilities.blade_storm.cooldownMult || 1) * 0.85; },
    },
    bladestorm_lightning: {
        id: 'bladestorm_lightning',
        name: 'Lightning Vortex',
        desc: 'Storm zaps enemies for bonus ⚡ DMG',
        icon: '⚡',
        color: '#ffeb3b',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.lightningTicks = true; mods.abilities.blade_storm.lightningDmgMult = 0.2; },
    },
    bladestorm_shredding: {
        id: 'bladestorm_shredding',
        name: 'Shredding Blades',
        desc: 'Storm applies bleed (3 DPS, 2s)',
        icon: '🩸',
        color: '#e91e63',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.bleedOnTick = true; mods.abilities.blade_storm.bleedDps = 3; mods.abilities.blade_storm.bleedDuration = 2000; },
    },
    bladestorm_eruption: {
        id: 'bladestorm_eruption',
        name: 'Blade Eruption',
        desc: 'Storm ends with a massive explosion',
        icon: '🌋',
        color: '#ff5722',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.endExplosion = true; mods.abilities.blade_storm.endExplosionRadius = 160; mods.abilities.blade_storm.endExplosionDmgMult = 1.0; },
    },

    // ── NEW BLADESTORM NODES ──

    bladestorm_speed: {
        id: 'bladestorm_speed',
        name: 'Eye of the Storm',
        desc: '+20% move speed during blade storm',
        icon: '💨',
        color: '#ce93d8',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.speedBoost = true; mods.abilities.blade_storm.speedMult = 1.20; },
    },
    bladestorm_vacuum: {
        id: 'bladestorm_vacuum',
        name: 'Vacuum Vortex',
        desc: 'Blade storm pulls enemies inward',
        icon: '🌀',
        color: '#ab47bc',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.vacuum = true; mods.abilities.blade_storm.vacuumForce = 80; },
    },
    bladestorm_frozen: {
        id: 'bladestorm_frozen',
        name: 'Frozen Blades',
        desc: 'Blade storm slows enemies by 30%',
        icon: '❄️',
        color: '#4fc3f7',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['blade_storm'] },
        apply(mods) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.slowOnTick = true; mods.abilities.blade_storm.slowFactor = 0.7; mods.abilities.blade_storm.slowDuration = 800; },
    },
    bladestorm_empowered: {
        id: 'bladestorm_empowered',
        name: 'Razor Storm',
        desc: '+20% blade storm tick damage',
        icon: '⚔️',
        color: '#ea80fc',
        category: 'ability:blade_storm',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['blade_storm'] },
        apply(mods, stacks) { mods.abilities.blade_storm = mods.abilities.blade_storm || {}; mods.abilities.blade_storm.dmgMult = (mods.abilities.blade_storm.dmgMult || 1) * 1.20; },
    },

    // ═══════════════════════════════════════════════════
    // ABILITY-SPECIFIC: GRAVITY PULL
    // ═══════════════════════════════════════════════════

    gravity_pull_radius: {
        id: 'gravity_pull_radius',
        name: 'Gravity Well',
        desc: '+25% gravity radius',
        icon: '🌑',
        color: '#7c4dff',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['gravity_pull'] },
        apply(mods, stacks) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.radiusMult = (mods.abilities.gravity_pull.radiusMult || 1) * 1.25; },
    },
    gravity_pull_cd: {
        id: 'gravity_pull_cd',
        name: 'Warp Affinity',
        desc: '-15% gravity pull cooldown',
        icon: '⏱️',
        color: '#7c4dff',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['gravity_pull'] },
        apply(mods) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.cooldownMult = (mods.abilities.gravity_pull.cooldownMult || 1) * 0.85; },
    },
    gravity_singularity: {
        id: 'gravity_singularity',
        name: 'Singularity',
        desc: 'Pull compresses enemies, +25% DMG taken',
        icon: '⚫',
        color: '#311b92',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { abilities: ['gravity_pull'] },
        apply(mods) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.singularity = true; mods.abilities.gravity_pull.singularityVulnMult = 1.25; mods.abilities.gravity_pull.singularityDuration = 3000; },
    },
    gravity_void_explosion: {
        id: 'gravity_void_explosion',
        name: 'Void Explosion',
        desc: 'Pull ends with a violent explosion',
        icon: '💥',
        color: '#6200ea',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { abilities: ['gravity_pull'] },
        apply(mods) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.endExplosion = true; mods.abilities.gravity_pull.endExplosionDmgMult = 0.8; mods.abilities.gravity_pull.endExplosionRadius = 120; },
    },

    // ── NEW GRAVITY PULL NODES ──

    gravity_pull_damage: {
        id: 'gravity_pull_damage',
        name: 'Crushing Gravity',
        desc: 'Pulled enemies take 3 DPS while pulled',
        icon: '💀',
        color: '#9575cd',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['gravity_pull'] },
        apply(mods) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.pullDps = 3; },
    },
    gravity_pull_duration: {
        id: 'gravity_pull_duration',
        name: 'Extended Pull',
        desc: '+0.3s pull duration',
        icon: '⏱️',
        color: '#b39ddb',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['gravity_pull'] },
        apply(mods, stacks) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.durationBonus = (mods.abilities.gravity_pull.durationBonus || 0) + 0.3; },
    },
    gravity_crush: {
        id: 'gravity_crush',
        name: 'Gravity Crush',
        desc: 'Tightly grouped enemies take +20% DMG',
        icon: '⚫',
        color: '#4527a0',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['gravity_pull'] },
        apply(mods) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.crushBonus = true; mods.abilities.gravity_pull.crushVulnMult = 1.20; mods.abilities.gravity_pull.crushRadius = 50; },
    },
    gravity_empowered: {
        id: 'gravity_empowered',
        name: 'Intense Field',
        desc: '+20% pull force',
        icon: '🌑',
        color: '#5e35b1',
        category: 'ability:gravity_pull',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['gravity_pull'] },
        apply(mods, stacks) { mods.abilities.gravity_pull = mods.abilities.gravity_pull || {}; mods.abilities.gravity_pull.forceMult = (mods.abilities.gravity_pull.forceMult || 1) * 1.20; },
    },

    // ═══════════════════════════════════════════════════
    // ABILITY-SPECIFIC: FREEZE PULSE
    // ═══════════════════════════════════════════════════

    freeze_pulse_radius: {
        id: 'freeze_pulse_radius',
        name: 'Permafrost',
        desc: '+25% freeze radius',
        icon: '❄️',
        color: '#40c4ff',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods, stacks) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.radiusMult = (mods.abilities.freeze_pulse.radiusMult || 1) * 1.25; },
    },
    freeze_pulse_duration: {
        id: 'freeze_pulse_duration',
        name: 'Deep Freeze',
        desc: '+0.5s freeze duration',
        icon: '❄️',
        color: '#80d8ff',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods, stacks) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.durationBonus = (mods.abilities.freeze_pulse.durationBonus || 0) + 0.5; },
    },
    freeze_pulse_cd: {
        id: 'freeze_pulse_cd',
        name: 'Frost Mastery',
        desc: '-20% freeze pulse cooldown',
        icon: '⏱️',
        color: '#40c4ff',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.cooldownMult = (mods.abilities.freeze_pulse.cooldownMult || 1) * 0.80; },
    },
    freeze_shatter: {
        id: 'freeze_shatter',
        name: 'Shatter',
        desc: 'Killing frozen enemies deals AoE ice DMG',
        icon: '💎',
        color: '#18ffff',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.shatter = true; mods.abilities.freeze_pulse.shatterRadius = 80; mods.abilities.freeze_pulse.shatterDmgMult = 0.6; },
    },
    freeze_chain: {
        id: 'freeze_chain',
        name: 'Frost Nova Chain',
        desc: 'Freeze spreads to 2 nearby enemies',
        icon: '❄️',
        color: '#00b8d4',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.chainFreeze = true; mods.abilities.freeze_pulse.chainCount = 2; mods.abilities.freeze_pulse.chainRange = 120; },
    },
    freeze_absolute_zero: {
        id: 'freeze_absolute_zero',
        name: 'Absolute Zero',
        desc: 'Frozen enemies take +30% more damage',
        icon: '🧊',
        color: '#e0f7fa',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.frozenVulnerability = true; mods.abilities.freeze_pulse.frozenVulnMult = 1.30; },
    },

    // ── NEW FREEZE PULSE NODES ──

    freeze_frostbite: {
        id: 'freeze_frostbite',
        name: 'Frostbite',
        desc: 'Frozen enemies take 4 cold DPS',
        icon: '🥶',
        color: '#00acc1',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.frostbiteDps = 4; },
    },
    freeze_ice_armor: {
        id: 'freeze_ice_armor',
        name: 'Ice Armor',
        desc: 'Freeze grants player 20% DR for 3s',
        icon: '🛡️',
        color: '#4dd0e1',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.iceArmor = true; mods.abilities.freeze_pulse.iceArmorDR = 0.20; mods.abilities.freeze_pulse.iceArmorDuration = 3000; },
    },
    freeze_empowered: {
        id: 'freeze_empowered',
        name: 'Glacial Force',
        desc: '+25% freeze pulse damage',
        icon: '❄️',
        color: '#0097a7',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods, stacks) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.dmgMult = (mods.abilities.freeze_pulse.dmgMult || 1) * 1.25; },
    },
    freeze_brittle: {
        id: 'freeze_brittle',
        name: 'Brittle',
        desc: 'Frozen enemies take +50% crit damage',
        icon: '💎',
        color: '#b2ebf2',
        category: 'ability:freeze_pulse',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { abilities: ['freeze_pulse'] },
        apply(mods) { mods.abilities.freeze_pulse = mods.abilities.freeze_pulse || {}; mods.abilities.freeze_pulse.brittleCritMult = 1.50; },
    },

    // ═══════════════════════════════════════════════════
    // PROC-SPECIFIC: EXPLOSIVE STRIKES
    // ═══════════════════════════════════════════════════

    proc_explosion_chance: {
        id: 'proc_explosion_chance',
        name: 'Volatile Mix',
        desc: '+5% explosion chance (cap 25%)',
        icon: '🔥',
        color: '#ff6d00',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 3,
        requires: { procs: ['explosive_strikes'] },
        apply(mods, stacks) {
            mods.procs.explosive_strikes = mods.procs.explosive_strikes || {};
            const bonus = (mods.procs.explosive_strikes.chanceBonus || 0) + 0.05;
            mods.procs.explosive_strikes.chanceBonus = Math.min(bonus, 0.15); // cap at +15% → total 25%
        },
    },
    proc_explosion_radius: {
        id: 'proc_explosion_radius',
        name: 'Blast Radius',
        desc: '+20% explosion radius',
        icon: '💥',
        color: '#ff9800',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { procs: ['explosive_strikes'] },
        apply(mods, stacks) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.radiusMult = (mods.procs.explosive_strikes.radiusMult || 1) * 1.20; },
    },
    proc_explosion_damage: {
        id: 'proc_explosion_damage',
        name: 'Bigger Boom',
        desc: '+15% explosion damage',
        icon: '💣',
        color: '#e65100',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        requires: { procs: ['explosive_strikes'] },
        apply(mods, stacks) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.dmgMult = (mods.procs.explosive_strikes.dmgMult || 1) * 1.15; },
    },
    proc_explosion_chain: {
        id: 'proc_explosion_chain',
        name: 'Inferno Chain',
        desc: 'Explosions can trigger more explosions',
        icon: '🔥',
        color: '#dd2c00',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { procs: ['explosive_strikes'] },
        apply(mods) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.chainExplosion = true; mods.procs.explosive_strikes.chainChance = 0.25; },
    },
    proc_explosion_burn: {
        id: 'proc_explosion_burn',
        name: 'Napalm',
        desc: 'Explosions leave fire (5 DPS, 2s)',
        icon: '🔥',
        color: '#ff8f00',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['explosive_strikes'] },
        apply(mods) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.burnOnExplosion = true; mods.procs.explosive_strikes.burnDps = 5; mods.procs.explosive_strikes.burnDuration = 2000; },
    },

    // ── NEW EXPLOSIVE STRIKES PROC NODES ──

    proc_explosion_slow: {
        id: 'proc_explosion_slow',
        name: 'Concussive Blast',
        desc: 'Explosions slow enemies (1.5s)',
        icon: '💫',
        color: '#ffa726',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['explosive_strikes'] },
        apply(mods) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.slowOnExplosion = true; mods.procs.explosive_strikes.slowDuration = 1500; mods.procs.explosive_strikes.slowFactor = 0.5; },
    },
    proc_explosion_vampiric: {
        id: 'proc_explosion_vampiric',
        name: 'Pyromaniac',
        desc: 'Heal 5% of explosion damage dealt',
        icon: '💉',
        color: '#d84315',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { procs: ['explosive_strikes'] },
        apply(mods) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.healPct = 0.05; },
    },
    proc_explosion_cluster: {
        id: 'proc_explosion_cluster',
        name: 'Cluster Bombs',
        desc: '20% chance: explosion spawns 3 mini-bombs',
        icon: '💣',
        color: '#ff3d00',
        category: 'proc:explosive_strikes',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { procs: ['explosive_strikes'] },
        apply(mods) { mods.procs.explosive_strikes = mods.procs.explosive_strikes || {}; mods.procs.explosive_strikes.clusterBomb = true; mods.procs.explosive_strikes.clusterChance = 0.20; mods.procs.explosive_strikes.clusterCount = 3; mods.procs.explosive_strikes.clusterDmgMult = 0.25; },
    },

    // ═══════════════════════════════════════════════════
    // PROC-SPECIFIC: CHAIN LIGHTNING
    // ═══════════════════════════════════════════════════

    proc_chain_targets: {
        id: 'proc_chain_targets',
        name: 'Longer Chain',
        desc: '+1 lightning jump',
        icon: '⚡',
        color: '#ffeb3b',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { procs: ['chain_lightning'] },
        apply(mods, stacks) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.extraJumps = (mods.procs.chain_lightning.extraJumps || 0) + 1; },
    },
    proc_chain_chance: {
        id: 'proc_chain_chance',
        name: 'Conduction',
        desc: '+5% lightning chance (cap 25%)',
        icon: '⚡',
        color: '#fdd835',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        requires: { procs: ['chain_lightning'] },
        apply(mods, stacks) {
            mods.procs.chain_lightning = mods.procs.chain_lightning || {};
            const bonus = (mods.procs.chain_lightning.chanceBonus || 0) + 0.05;
            mods.procs.chain_lightning.chanceBonus = Math.min(bonus, 0.13); // cap +13% → total 25%
        },
    },
    proc_chain_range: {
        id: 'proc_chain_range',
        name: 'Extended Arc',
        desc: '+20% lightning range',
        icon: '⚡',
        color: '#fff176',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 2,
        requires: { procs: ['chain_lightning'] },
        apply(mods, stacks) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.rangeMult = (mods.procs.chain_lightning.rangeMult || 1) * 1.20; },
    },
    proc_chain_damage: {
        id: 'proc_chain_damage',
        name: 'Overcharge',
        desc: '+25% chain lightning damage',
        icon: '⚡',
        color: '#ffd600',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        requires: { procs: ['chain_lightning'] },
        apply(mods, stacks) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.dmgMult = (mods.procs.chain_lightning.dmgMult || 1) * 1.25; },
    },
    proc_chain_stun: {
        id: 'proc_chain_stun',
        name: 'Paralyzing Bolt',
        desc: 'Lightning stuns last target 0.5s',
        icon: '⚡',
        color: '#e0e000',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { procs: ['chain_lightning'] },
        apply(mods) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.stunLastTarget = true; mods.procs.chain_lightning.stunDuration = 500; },
    },

    // ── NEW CHAIN LIGHTNING PROC NODES ──

    proc_chain_burn: {
        id: 'proc_chain_burn',
        name: 'Electro-Burn',
        desc: 'Lightning applies burn (3 DPS, 2s)',
        icon: '🔥',
        color: '#ffca28',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['chain_lightning'] },
        apply(mods) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.burnOnJump = true; mods.procs.chain_lightning.burnDps = 3; mods.procs.chain_lightning.burnDuration = 2000; },
    },
    proc_chain_splash: {
        id: 'proc_chain_splash',
        name: 'Arc Splash',
        desc: 'Each jump also does small AoE damage',
        icon: '⚡',
        color: '#fff9c4',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { procs: ['chain_lightning'] },
        apply(mods) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.splashOnJump = true; mods.procs.chain_lightning.splashRadius = 40; mods.procs.chain_lightning.splashDmgMult = 0.25; },
    },
    proc_chain_energize: {
        id: 'proc_chain_energize',
        name: 'Energize',
        desc: 'Lightning reduces ability CDs by 0.3s per jump',
        icon: '🔋',
        color: '#c0ca33',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        requires: { procs: ['chain_lightning'] },
        apply(mods) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.energize = true; mods.procs.chain_lightning.energizePerJump = 0.3; },
    },
    proc_chain_fork: {
        id: 'proc_chain_fork',
        name: 'Forked Lightning',
        desc: 'Lightning forks — hits 2 enemies per jump',
        icon: '⚡',
        color: '#ffe082',
        category: 'proc:chain_lightning',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { procs: ['chain_lightning'] },
        apply(mods) { mods.procs.chain_lightning = mods.procs.chain_lightning || {}; mods.procs.chain_lightning.fork = true; mods.procs.chain_lightning.forkTargets = 2; },
    },

    // ═══════════════════════════════════════════════════
    // PROC-SPECIFIC: HEAVY CRIT
    // ═══════════════════════════════════════════════════

    proc_crit_damage: {
        id: 'proc_crit_damage',
        name: 'Devastating Crits',
        desc: '+20% crit bonus damage',
        icon: '💎',
        color: '#ff1744',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        requires: { procs: ['heavy_crit'] },
        apply(mods, stacks) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.extraDmgMult = (mods.procs.heavy_crit.extraDmgMult || 1) * 1.20; },
    },
    proc_crit_chance_global: {
        id: 'proc_crit_chance_global',
        name: 'Keen Eye',
        desc: '+3% global crit chance',
        icon: '🎯',
        color: '#d50000',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_COMMON,
        maxStacks: 3,
        requires: { procs: ['heavy_crit'] },
        apply(mods, stacks) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.globalCritBonus = (mods.procs.heavy_crit.globalCritBonus || 0) + 0.03; },
    },
    proc_crit_explosion: {
        id: 'proc_crit_explosion',
        name: 'Critical Mass',
        desc: 'Crits cause a small explosion (r50)',
        icon: '💥',
        color: '#ff1744',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.critExplosion = true; mods.procs.heavy_crit.critExplosionRadius = 50; mods.procs.heavy_crit.critExplosionDmgMult = 0.3; },
    },
    proc_crit_chain: {
        id: 'proc_crit_chain',
        name: 'Crit Streak',
        desc: 'Each crit increases next crit chance +5%',
        icon: '🔥',
        color: '#ff5252',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.critStreak = true; mods.procs.heavy_crit.critStreakBonus = 0.05; mods.procs.heavy_crit.critStreakMax = 0.25; },
    },

    // ── NEW HEAVY CRIT PROC NODES ──

    proc_crit_lifesteal: {
        id: 'proc_crit_lifesteal',
        name: 'Vampiric Crits',
        desc: 'Crits heal 5% of damage dealt',
        icon: '🧛',
        color: '#c62828',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.critLifesteal = true; mods.procs.heavy_crit.critLifestealPct = 0.05; },
    },
    proc_crit_slow: {
        id: 'proc_crit_slow',
        name: 'Crippling Crits',
        desc: 'Crits slow target 30% for 1.5s',
        icon: '🐌',
        color: '#ef9a9a',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.critSlow = true; mods.procs.heavy_crit.critSlowFactor = 0.7; mods.procs.heavy_crit.critSlowDuration = 1500; },
    },
    proc_crit_execute: {
        id: 'proc_crit_execute',
        name: 'Coup de Grâce',
        desc: 'Crits vs enemies below 15% HP: instant kill',
        icon: '💀',
        color: '#b71c1c',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.execute = true; mods.procs.heavy_crit.executeThreshold = 0.15; },
    },
    proc_crit_shockwave: {
        id: 'proc_crit_shockwave',
        name: 'Crit Nova',
        desc: 'Every 3rd crit triggers a free shockwave',
        icon: '💥',
        color: '#e53935',
        category: 'proc:heavy_crit',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        requires: { procs: ['heavy_crit'] },
        apply(mods) { mods.procs.heavy_crit = mods.procs.heavy_crit || {}; mods.procs.heavy_crit.critNova = true; mods.procs.heavy_crit.critNovaEveryN = 3; mods.procs.heavy_crit.critNovaRadius = 80; mods.procs.heavy_crit.critNovaDmgMult = 0.5; },
    },

    // ═══════════════════════════════════════════════════
    // GLOBAL NODES (rare, category-agnostic)
    // ═══════════════════════════════════════════════════

    global_damage_boost: {
        id: 'global_damage_boost',
        name: 'Power Surge',
        desc: '+8% all damage',
        icon: '⚡',
        color: '#f44336',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.damageMult = (mods.global.damageMult || 1) * 1.08; },
    },
    global_cooldown_reduction: {
        id: 'global_cooldown_reduction',
        name: 'Temporal Flux',
        desc: '-8% all cooldowns',
        icon: '⏱️',
        color: '#7c4dff',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.cooldownMult = (mods.global.cooldownMult || 1) * 0.92; },
    },
    global_elemental_fury: {
        id: 'global_elemental_fury',
        name: 'Elemental Fury',
        desc: 'On kill: random elemental burst',
        icon: '🌈',
        color: '#f50057',
        category: 'global',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.global.elementalFury = true; mods.global.elementalFuryRadius = 70; mods.global.elementalFuryDmgMult = 0.35; },
    },
    global_momentum: {
        id: 'global_momentum',
        name: 'Momentum',
        desc: 'Kills within 3s grant +5% speed (max +30%)',
        icon: '🏃',
        color: '#00e676',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.momentum = true; mods.global.momentumSpeedPer = 0.05; mods.global.momentumMax = 0.30; mods.global.momentumWindow = 3000; },
    },
    global_glass_cannon: {
        id: 'global_glass_cannon',
        name: 'Glass Cannon',
        desc: '+25% all DMG, but -15% max HP',
        icon: '🔮',
        color: '#d500f9',
        category: 'global',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.global.damageMult = (mods.global.damageMult || 1) * 1.25; mods.global.glassCannonHpMult = 0.85; },
    },
    global_overcharge: {
        id: 'global_overcharge',
        name: 'Overcharge',
        desc: '+15% ability DMG, -10% ability CD',
        icon: '⚡',
        color: '#aa00ff',
        category: 'global',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.global.abilityDmgMult = (mods.global.abilityDmgMult || 1) * 1.15; mods.global.cooldownMult = (mods.global.cooldownMult || 1) * 0.90; },
    },

    // ── NEW GLOBAL NODES ──

    global_bloodthirst: {
        id: 'global_bloodthirst',
        name: 'Bloodthirst',
        desc: 'Kills heal 2% max HP',
        icon: '❤️',
        color: '#c62828',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.killHealPct = (mods.global.killHealPct || 0) + 0.02; },
    },
    global_adrenaline: {
        id: 'global_adrenaline',
        name: 'Adrenaline Rush',
        desc: 'Kills grant +5% speed for 3s (max +25%)',
        icon: '💉',
        color: '#00e676',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.global.adrenaline = true; mods.global.adrenalineSpeedPer = 0.05; mods.global.adrenalineMax = 0.25; mods.global.adrenalineDuration = 3000; },
    },
    global_executioner: {
        id: 'global_executioner',
        name: 'Executioner',
        desc: '+15% DMG to enemies below 25% HP',
        icon: '⚰️',
        color: '#4a148c',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.executeMult = 1.15; mods.global.executeThreshold = 0.25; },
    },
    global_last_stand: {
        id: 'global_last_stand',
        name: 'Last Stand',
        desc: 'Below 20% HP: +35% DMG, -20% DMG taken',
        icon: '🔥',
        color: '#ff1744',
        category: 'global',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.global.lastStand = true; mods.global.lastStandThreshold = 0.20; mods.global.lastStandDmgMult = 1.35; mods.global.lastStandDRMult = 0.80; },
    },
    global_thorns: {
        id: 'global_thorns',
        name: 'Thorns',
        desc: 'Reflect 15% damage taken back to enemies',
        icon: '🌵',
        color: '#558b2f',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.thornsPct = (mods.global.thornsPct || 0) + 0.15; },
    },
    global_soul_collector: {
        id: 'global_soul_collector',
        name: 'Soul Collector',
        desc: 'Each room kill grants +2% DMG (max +20%)',
        icon: '👻',
        color: '#6a1b9a',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.soulCollector = true; mods.global.soulCollectorPer = 0.02; mods.global.soulCollectorMax = 0.20; },
    },
    global_versatile: {
        id: 'global_versatile',
        name: 'Versatile Fighter',
        desc: '+5% melee DMG + 5% dagger DMG',
        icon: '🤺',
        color: '#ff6e40',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 3,
        apply(mods, stacks) { mods.melee.damageMult = (mods.melee.damageMult || 1) * 1.05; mods.dagger.damageMult = (mods.dagger.damageMult || 1) * 1.05; },
    },
    global_evasion: {
        id: 'global_evasion',
        name: 'Evasion',
        desc: '8% chance to dodge damage',
        icon: '💨',
        color: '#78909c',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.dodgeChance = (mods.global.dodgeChance || 0) + 0.08; },
    },
    global_rampage: {
        id: 'global_rampage',
        name: 'Rampage',
        desc: 'Every 5 kills: 3s of +40% speed + DMG',
        icon: '😤',
        color: '#ff3d00',
        category: 'global',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.global.rampage = true; mods.global.rampageKillsNeeded = 5; mods.global.rampageDuration = 3000; mods.global.rampageSpeedMult = 1.40; mods.global.rampageDmgMult = 1.40; },
    },
    global_second_life: {
        id: 'global_second_life',
        name: 'Second Life',
        desc: 'Revive once with 30% HP on death',
        icon: '✝️',
        color: '#ffd600',
        category: 'global',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.global.secondLife = true; mods.global.secondLifeHealPct = 0.30; },
    },
    global_aura_of_decay: {
        id: 'global_aura_of_decay',
        name: 'Aura of Decay',
        desc: 'Nearby enemies take 2 DPS (r80)',
        icon: '☠️',
        color: '#76ff03',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.auraDecay = true; mods.global.auraDecayDps = (mods.global.auraDecayDps || 0) + 2; mods.global.auraDecayRadius = 80; },
    },
    global_crit_momentum: {
        id: 'global_crit_momentum',
        name: 'Critical Momentum',
        desc: 'Crits grant +8% move speed for 2s',
        icon: '🏃',
        color: '#ff6d00',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.global.critMomentum = true; mods.global.critMomentumSpeed = 0.08; mods.global.critMomentumDuration = 2000; },
    },
    global_battle_hardened: {
        id: 'global_battle_hardened',
        name: 'Battle Hardened',
        desc: '-5% damage taken',
        icon: '🛡️',
        color: '#546e7a',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 3,
        apply(mods, stacks) { mods.global.damageTakenMult = (mods.global.damageTakenMult || 1) * 0.95; },
    },
    global_scavenger: {
        id: 'global_scavenger',
        name: 'Scavenger',
        desc: '+15% XP gain + 10% coin gain',
        icon: '💰',
        color: '#ffd54f',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.xpGainMult = (mods.global.xpGainMult || 1) * 1.15; mods.global.coinGainMult = (mods.global.coinGainMult || 1) * 1.10; },
    },
    global_focus: {
        id: 'global_focus',
        name: 'Focus',
        desc: '+4% global crit chance',
        icon: '🎯',
        color: '#ff5252',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.critBonus = (mods.global.critBonus || 0) + 0.04; },
    },
    global_berserker_soul: {
        id: 'global_berserker_soul',
        name: "Berserker's Soul",
        desc: 'Lower HP = more DMG (up to +30% at 1 HP)',
        icon: '🔴',
        color: '#d50000',
        category: 'global',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.global.berserkerSoul = true; mods.global.berserkerSoulMaxBonus = 0.30; },
    },
    global_shield_on_kill: {
        id: 'global_shield_on_kill',
        name: 'Siphon Shield',
        desc: 'Kills grant a 10 HP shield (max 30)',
        icon: '🛡️',
        color: '#64ffda',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.shieldOnKill = true; mods.global.shieldOnKillAmount = 10; mods.global.shieldMax = 30; },
    },

    // ═══════════════════════════════════════════════════
    // SYNERGY / CROSS-CATEGORY NODES
    // These combine effects across different combat systems
    // ═══════════════════════════════════════════════════

    synergy_blade_dance: {
        id: 'synergy_blade_dance',
        name: 'Blade Dance',
        desc: 'Melee kills boost next dagger +30% DMG',
        icon: '💃',
        color: '#ff7043',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.bladeDance = true; mods.global.bladeDanceDmgMult = 1.30; },
    },
    synergy_assassin_path: {
        id: 'synergy_assassin_path',
        name: "Assassin's Path",
        desc: 'Dashing auto-fires a dagger forward',
        icon: '🗡️',
        color: '#26a69a',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.dashDagger = true; mods.global.dashDaggerDmgMult = 0.60; },
    },
    synergy_frozen_strike: {
        id: 'synergy_frozen_strike',
        name: 'Frozen Strike',
        desc: '+25% melee DMG vs frozen/slowed enemies',
        icon: '❄️',
        color: '#4dd0e1',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.global.frozenStrikeMult = 1.25; },
    },
    synergy_burning_blades: {
        id: 'synergy_burning_blades',
        name: 'Burning Blades',
        desc: '+20% dagger DMG vs burning enemies',
        icon: '🔥',
        color: '#ff8a65',
        category: 'global',
        rarity: NODE_RARITY_UNCOMMON,
        maxStacks: 1,
        apply(mods) { mods.global.burningBladesMult = 1.20; },
    },
    synergy_storm_caller: {
        id: 'synergy_storm_caller',
        name: 'Storm Caller',
        desc: 'Ability use boosts proc chance +10% for 5s',
        icon: '🌩️',
        color: '#7c4dff',
        category: 'global',
        rarity: NODE_RARITY_EPIC,
        maxStacks: 1,
        apply(mods) { mods.global.stormCaller = true; mods.global.stormCallerProcBonus = 0.10; mods.global.stormCallerDuration = 5000; },
    },
    synergy_combo_master: {
        id: 'synergy_combo_master',
        name: 'Combo Master',
        desc: 'Alternating melee/dagger: +20% DMG',
        icon: '🔄',
        color: '#ff4081',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.comboMaster = true; mods.global.comboMasterMult = 1.20; },
    },
    synergy_elemental_mastery: {
        id: 'synergy_elemental_mastery',
        name: 'Elemental Mastery',
        desc: 'Status effects deal +25% more damage',
        icon: '🌈',
        color: '#e040fb',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.statusDmgMult = (mods.global.statusDmgMult || 1) * 1.25; },
    },
    synergy_war_machine: {
        id: 'synergy_war_machine',
        name: 'War Machine',
        desc: '+8% all DMG, +5% attack speed, -5% max HP',
        icon: '⚙️',
        color: '#757575',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.damageMult = (mods.global.damageMult || 1) * 1.08; mods.melee.cooldownMult = (mods.melee.cooldownMult || 1) * 0.95; mods.global.glassCannonHpMult = (mods.global.glassCannonHpMult || 1) * 0.95; },
    },
    synergy_dash_melee: {
        id: 'synergy_dash_melee',
        name: 'Blitz Strike',
        desc: 'Dashing through enemies auto-melees them',
        icon: '⚔️',
        color: '#ffab00',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 1,
        apply(mods) { mods.global.dashMelee = true; mods.global.dashMeleeDmgMult = 0.50; },
    },
    synergy_proc_amplifier: {
        id: 'synergy_proc_amplifier',
        name: 'Proc Amplifier',
        desc: '+5% proc chance for all procs',
        icon: '📡',
        color: '#7e57c2',
        category: 'global',
        rarity: NODE_RARITY_RARE,
        maxStacks: 2,
        apply(mods, stacks) { mods.global.procChanceBonus = (mods.global.procChanceBonus || 0) + 0.05; },
    },
    synergy_ability_echo: {
        id: 'synergy_ability_echo',
        name: 'Ability Echo',
        desc: '15% chance: ability use costs no cooldown',
        icon: '🔮',
        color: '#aa00ff',
        category: 'global',
        rarity: NODE_RARITY_LEGENDARY,
        maxStacks: 1,
        apply(mods) { mods.global.abilityEchoChance = 0.15; },
    },
};

/** All node IDs */
export const NODE_IDS = Object.keys(NODE_DEFINITIONS);

/** Get a node definition by ID */
export function getNode(id) {
    return NODE_DEFINITIONS[id] || null;
}

/** Get all nodes of a given category */
export function getNodesByCategory(category) {
    return NODE_IDS.filter(id => NODE_DEFINITIONS[id].category === category).map(id => NODE_DEFINITIONS[id]);
}

/** Get all base category names (without ability/proc prefixes) */
export const BASE_CATEGORIES = ['melee', 'dagger', 'dash', 'global'];

/**
 * Create a fresh combatMods object for a new run.
 * Game systems read these modifiers to adjust behavior.
 */
export function createDefaultCombatMods() {
    return {
        melee: {},
        dagger: {},
        dash: {},
        abilities: {},   // keyed by abilityId
        procs: {},        // keyed by procId
        global: {},
    };
}
